# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    golang-x:
      patterns:
        - "golang.org/x/*"
    k8s-sigs:
      patterns:
        - "sigs.k8s.io/*"
    spf13:
      patterns:
        - "github.com/spf13/cobra"
        - "github.com/spf13/viper"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github:
      patterns:
        - "actions/*"
        - "github/*"
- package-ecosystem: "docker"
  directory: /
  schedule:
    interval: "weekly"
