# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: 'Checkout Repository'
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70
